
AboutController:
  path: /connexion
  controller: App\Controller\AboutController::connexion

CommentController:
  path: /comment
  controller: App\Controller\CommentController::comment

DashboardController:
  path: /admin
  controller: App\Controller\Admin\DashboardController::admin

EditController:
  path: /edit
  controller: App\Controller\EditController::edit

Index:
  path: /
  controller: App\Controller\HomeController::index

Login:
  path: /login
  controller: App\Controller\SecurityController::login

Profile:
  path: /profile
  controller: App\Controller\ProfileController::profile


RegistrationController:
  path: /register
  controller: App\Controller\RegistrationController::register

RegistrationPro:
  path: /registerpro
  controller: App\Controller\RegistrationController::registerpro

RegistrationPart:
  path: /registerpart
  controller: App\Controller\RegistrationController::registerpart